### ISSUE TITLE
请问blocklist在哪里啊

### ISSUE THREAD

**Issue by zkyhzxf** [Cansiny0320/bilibili-block-plus#2]
根本找不到可以填写的地方

**Comment by Cansiny0320** [comment]
修改了一下 忘记更新文档了 现在这么使用
点一下这个图标
![image](https://user-images.githubusercontent.com/51797219/184574912-c25b2057-f12f-45a7-b901-168afa9ea16d.png)
然后填写你要屏蔽的用户名 每行一个
![image](https://user-images.githubusercontent.com/51797219/184574944-a6791015-f053-4544-a923-4078649bf4c3.png)
最后再点一下图标保存（这步要做 不点图标不会保存）

最后刷新页面就有效果了

**Comment by Cansiny0320** [comment]
文档已更新
